"use client";

import { motion } from "motion/react";
import { ArrowDown, ArrowUpRight, Check, Circle } from "lucide-react";

const ease = [0.22, 1, 0.36, 1] as const;
const words = ["BUILD", "STRATEGY", "FUNNEL", "DECK", "LAUNCH", "CLIENT", "AUDIENCE"];
const funnel = ["Visitor", "Lead", "Qualified", "Proposal", "Client"];
const slides = ["Title", "What We Heard", "Opportunity", "Strategy", "Media Plan", "CTA"];

export default function BuilderStoryLab() {
  return (
    <main className="min-h-screen bg-[#090909] text-[#f2f2ee] selection:bg-[#819cff] selection:text-black">
      <div className="pointer-events-none fixed inset-0 z-50 opacity-[.035] [background-image:url('data:image/svg+xml,%3Csvg_viewBox=%220_0_160_160%22_xmlns=%22http://www.w3.org/2000/svg%22%3E%3Cfilter_id=%22n%22%3E%3CfeTurbulence_type=%22fractalNoise%22_baseFrequency=%22.9%22_numOctaves=%224%22_stitchTiles=%22stitch%22/%3E%3C/filter%3E%3Crect_width=%22100%25%22_height=%22100%25%22_filter=%22url(%23n)%22_opacity=%221%22/%3E%3C/svg%3E')]" />

      <header className="mx-auto flex max-w-[1500px] items-end justify-between border-b border-white/15 px-5 pb-6 pt-24 sm:px-10 lg:px-16 lg:pt-32">
        <div>
          <Eyebrow>434 / Visual Experiments / 01</Eyebrow>
          <h1 className="mt-4 max-w-4xl text-[clamp(3.2rem,8vw,8.5rem)] font-medium leading-[.78] tracking-[-.075em]">Builder<br /><span className="font-serif font-normal italic text-white/45">Story Lab</span></h1>
        </div>
        <p className="hidden max-w-[230px] text-right text-xs leading-5 text-white/45 md:block">Five vertical studies for showing the distance between an idea and a working system.</p>
      </header>

      <section className="mx-auto max-w-[1500px] px-5 py-10 sm:px-10 lg:px-16 lg:py-16">
        <div className="mb-10 flex items-center justify-between border-b border-white/15 pb-4">
          <Eyebrow>Capture-ready prototypes</Eyebrow><Eyebrow>9:16 / Scroll to explore</Eyebrow>
        </div>
        <div className="grid items-start gap-x-6 gap-y-20 md:grid-cols-2 xl:grid-cols-3">
          <Prototype index="01" title="Split Source → Output" note="Input becomes strategy."><SourceOutput /></Prototype>
          <Prototype index="02" title="Image → Text Construction" note="Language becomes image."><TextConstruction /></Prototype>
          <Prototype index="03" title="Funnel Being Built" note="Watch the funnel build itself."><FunnelBuild /></Prototype>
          <Prototype index="04" title="Deck Assembly" note="Notes become a client-ready deck."><DeckAssembly /></Prototype>
          <Prototype index="05" title="Builder Spotlight" note="Spotlight the builders behind the work."><BuilderSpotlight /></Prototype>
          <Prototype index="06" title="Brief → Blueprint" note="Turn ambiguity into architecture."><BriefBlueprint /></Prototype>
          <Prototype index="07" title="Signal Finder" note="Find the line worth building around."><SignalFinder /></Prototype>
          <Prototype index="08" title="Offer Anatomy" note="Show what makes the offer work."><OfferAnatomy /></Prototype>
          <Prototype index="09" title="Build Timeline" note="One idea, five decisive moments."><BuildTimeline /></Prototype>
          <Prototype index="10" title="Before → System" note="Chaos gains a repeatable shape."><BeforeSystem /></Prototype>
          <Prototype index="11" title="Audience Layers" note="A portrait built from customer language."><AudienceLayers /></Prototype>
          <Prototype index="12" title="Decision Engine" note="Show the logic behind the work."><DecisionEngine /></Prototype>
          <Prototype index="13" title="Proof Stack" note="Turn evidence into momentum."><ProofStack /></Prototype>
          <Prototype index="14" title="Message Compression" note="A long brief becomes one clear line."><MessageCompression /></Prototype>
          <Prototype index="15" title="Launch Sequence" note="Watch the campaign leave the ground."><LaunchSequence /></Prototype>
          <Prototype index="16" title="Builder Manifesto" note="Introduce the mind behind the system."><BuilderManifesto /></Prototype>
          <Prototype index="17" title="System X-Ray" note="Reveal everything under the outcome."><SystemXray /></Prototype>
          <Prototype index="18" title="Iteration Wall" note="The discarded work tells the story too."><IterationWall /></Prototype>
          <Prototype index="19" title="Metric Translation" note="Numbers become a human story."><MetricTranslation /></Prototype>
          <Prototype index="20" title="The Handoff" note="The system keeps working after launch."><TheHandoff /></Prototype>
        </div>
      </section>
    </main>
  );
}

function Prototype({ index, title, note, children }: { index: string; title: string; note: string; children: React.ReactNode }) {
  return <article>
    <div className="mb-3 flex items-end justify-between gap-4"><div><Eyebrow>{index} / Prototype</Eyebrow><h2 className="mt-2 text-lg font-medium tracking-[-.03em]">{title}</h2></div><p className="max-w-[130px] text-right text-[10px] leading-4 text-white/35">{note}</p></div>
    <div className="relative aspect-[9/16] overflow-hidden border border-white/20 bg-[#e9e9e4] text-[#101010] shadow-[0_30px_80px_rgba(0,0,0,.35)]">{children}<FrameMarks /></div>
  </article>;
}

function SourceOutput() {
  return <div className="relative grid h-full grid-cols-2">
    <div className="flex flex-col bg-[#111] p-5 text-white"><SmallLabel>Source / Client voice</SmallLabel><div className="my-auto"><p className="font-serif text-[clamp(1.45rem,3vw,2.4rem)] leading-[.98] tracking-[-.04em]">“We need a way to turn attention into actual conversations.”</p><div className="mt-8 space-y-2 font-mono text-[8px] uppercase tracking-[.08em] text-white/35"><p>Audience: Founders</p><p>Offer: Growth Sprint</p><p>Timeline: 30 Days</p><p>Constraint: No paid media</p></div></div><SmallLabel>Raw input / 00:01</SmallLabel></div>
    <div className="relative flex flex-col overflow-hidden bg-[#ededE8] p-5"><SmallLabel>Output / Funnel v1</SmallLabel><div className="my-auto space-y-3">{["Founder insight", "Proof-led story", "Diagnostic CTA", "Sales conversation"].map((item, i) => <motion.div key={item} initial={{ opacity: 0, x: -18 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: false, amount: .7 }} transition={{ delay: .3 + i * .18, duration: .55, ease }} className="border-t border-black/25 pt-2"><span className="font-mono text-[7px] text-black/35">0{i + 1}</span><p className="mt-1 text-sm font-medium tracking-[-.03em]">{item}</p></motion.div>)}</div><div className="flex items-center gap-2 font-mono text-[7px] uppercase tracking-widest"><Check className="h-3 w-3" />System ready</div>
      <motion.div initial={{ scaleY: 1 }} whileInView={{ scaleY: 0 }} viewport={{ once: false, amount: .4 }} transition={{ duration: 1.4, ease }} style={{ transformOrigin: "top" }} className="absolute inset-0 bg-[#111]" />
    </div><motion.div initial={{ height: 0 }} whileInView={{ height: "100%" }} viewport={{ once: false }} transition={{ duration: 1.1, ease }} className="absolute left-1/2 top-0 z-10 w-px bg-[#829dff]" />
    <p className="absolute left-1/2 top-1/2 z-20 -translate-x-1/2 -translate-y-1/2 rotate-90 bg-[#829dff] px-2 py-1 font-mono text-[6px] uppercase tracking-widest">Transform</p>
  </div>;
}

function TextConstruction() {
  return <div className="relative h-full overflow-hidden bg-[#e8e8e3] p-5"><div className="flex justify-between"><SmallLabel>Text / Image study</SmallLabel><SmallLabel>02—07</SmallLabel></div>
    <motion.div initial={{ opacity: .15 }} whileInView={{ opacity: 1 }} viewport={{ once: false, amount: .5 }} transition={{ duration: 1.2 }} className="absolute inset-x-[-12%] top-[16%] rotate-[-8deg] font-mono text-[10px] font-bold leading-[.82] tracking-[-.09em] text-black">{Array.from({ length: 31 }, (_, row) => <div key={row} className="whitespace-nowrap" style={{ paddingLeft: `${Math.abs(15 - row) * 4}px`, opacity: .18 + (1 - Math.abs(15 - row) / 16) * .82 }}>{Array.from({ length: 9 }, (_, i) => <span key={i} className="mr-2">{words[(row + i) % words.length]}</span>)}</div>)}</motion.div>
    <div className="absolute inset-x-5 bottom-5 border-t border-black/30 pt-4"><p className="max-w-[85%] text-4xl font-medium leading-[.85] tracking-[-.06em]">Build the image<br /><span className="font-serif italic font-normal text-black/35">from the idea.</span></p><div className="mt-5 flex justify-between"><SmallLabel>7 words / 1 system</SmallLabel><ArrowDown className="h-4 w-4" /></div></div>
  </div>;
}

function FunnelBuild() {
  return <div className="relative h-full bg-[#0d0d0d] p-5 text-white"><div className="flex justify-between"><SmallLabel>Conversion architecture</SmallLabel><SmallLabel>Live build</SmallLabel></div><div className="absolute left-5 right-5 top-[18%] bottom-[18%]">
    <svg className="absolute inset-0 h-full w-full" preserveAspectRatio="none"><motion.path d="M30 25 C220 60 20 145 210 190 S30 325 215 385 S30 500 210 565" fill="none" stroke="#535353" strokeWidth="1" initial={{ pathLength: 0 }} whileInView={{ pathLength: 1 }} viewport={{ once: false, amount: .6 }} transition={{ duration: 2.6, ease }} /><motion.circle r="4" fill="#9caeff" initial={{ offsetDistance: "0%" }} whileInView={{ offsetDistance: "100%" }} viewport={{ once: false }} transition={{ duration: 3.2, ease }} style={{ offsetPath: "path('M30 25 C220 60 20 145 210 190 S30 325 215 385 S30 500 210 565')", filter: "drop-shadow(0 0 8px #9caeff)" }} /></svg>
    <div className="relative flex h-full flex-col justify-between">{funnel.map((item, i) => <motion.div key={item} initial={{ opacity: 0, y: 10 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: false, amount: .8 }} transition={{ delay: i * .35, duration: .5 }} className={`flex items-center gap-3 ${i % 2 ? "ml-auto flex-row-reverse text-right" : ""}`}><span className={`grid h-10 w-10 place-items-center rounded-full border ${i === 4 ? "border-[#9caeff] bg-[#9caeff] text-black" : "border-white/30 bg-[#111]"}`}><span className="font-mono text-[8px]">0{i + 1}</span></span><div><p className="text-xl font-medium tracking-[-.05em]">{item}</p><p className="font-mono text-[7px] uppercase tracking-widest text-white/30">{["Arrives", "Signals", "Fits", "Decides", "Begins"][i]}</p></div></motion.div>)}</div>
  </div><div className="absolute bottom-5 left-5 right-5 flex items-end justify-between border-t border-white/15 pt-4"><p className="max-w-[190px] text-2xl font-medium leading-[.95] tracking-[-.05em]">Watch the funnel<br />build itself.</p><Circle className="h-3 w-3 fill-[#9caeff] text-[#9caeff]" /></div></div>;
}

function DeckAssembly() {
  return <div className="relative grid h-full grid-cols-[.42fr_.58fr] bg-[#e8e8e3]"><div className="border-r border-black/20 bg-[#d8d8d2] p-4"><SmallLabel>Client intake</SmallLabel><div className="mt-16 space-y-6 font-serif text-xs italic leading-4 text-black/55"><p>“make it feel simple”</p><p>Founders know the problem, but not the cost.</p><p className="line-through opacity-40">Lead with capabilities</p><p>Lead with the change.</p><p>Need proof + clear next step.</p></div><div className="absolute bottom-5 left-4"><SmallLabel>Notes / 14 lines</SmallLabel></div></div>
    <div className="relative overflow-hidden bg-[#111] p-4 text-white"><SmallLabel>Sales deck / 06 slides</SmallLabel><div className="mt-12 space-y-[-2px]">{slides.map((slide, i) => <motion.div key={slide} initial={{ opacity: 0, x: 40, rotate: 3 }} whileInView={{ opacity: 1, x: 0, rotate: 0 }} viewport={{ once: false, amount: .7 }} transition={{ delay: i * .13, duration: .6, ease }} className="relative aspect-[16/9] border border-white/20 bg-[#e8e8e3] p-3 text-black shadow-[0_-8px_20px_rgba(0,0,0,.25)]"><span className="font-mono text-[6px] text-black/35">0{i + 1}</span><p className="absolute bottom-3 left-3 max-w-[85%] text-[13px] font-medium leading-[.9] tracking-[-.05em]">{slide}</p>{i === 3 && <div className="absolute right-3 top-3 h-5 w-5 rounded-full bg-[#91a6ff]" />}</motion.div>)}</div><p className="absolute bottom-5 right-4 font-serif text-sm italic text-white/45">Notes, made persuasive.</p></div>
  </div>;
}

function BuilderSpotlight() {
  return <div className="relative h-full bg-[#ededE8] p-5"><div className="flex justify-between"><SmallLabel>Builder spotlight / 001</SmallLabel><SmallLabel>434</SmallLabel></div><div className="absolute left-5 right-5 top-[13%] grid h-[54%] grid-cols-2 border-y border-black/25"><div className="relative overflow-hidden border-r border-black/25 bg-[#cecec8] p-3"><SmallLabel>Started with</SmallLabel><div className="absolute inset-x-3 top-[28%] space-y-3 font-mono text-[7px] uppercase text-black/40"><p className="border-b border-black/20 pb-2">Scattered notes</p><p className="border-b border-black/20 pb-2">One good offer</p><p className="border-b border-black/20 pb-2">No repeatable path</p></div><p className="absolute bottom-3 text-4xl font-medium tracking-[-.08em]">01</p></div>
    <div className="relative overflow-hidden bg-[#111] p-3 text-white"><SmallLabel>Built</SmallLabel><motion.div initial={{ scale: .5, opacity: 0 }} whileInView={{ scale: 1, opacity: 1 }} viewport={{ once: false, amount: .6 }} transition={{ duration: .9, ease }} className="absolute left-1/2 top-[42%] h-36 w-36 -translate-x-1/2 -translate-y-1/2 rounded-full border border-white/30"><div className="absolute inset-4 rounded-full border border-white/30" /><div className="absolute inset-9 rounded-full bg-[#91a6ff]" /></motion.div><p className="absolute bottom-3 text-4xl font-medium tracking-[-.08em]">10×</p></div></div>
    <div className="absolute inset-x-5 bottom-5"><p className="font-serif text-base italic text-black/45">Meet the builder</p><h3 className="mt-2 text-4xl font-medium leading-[.88] tracking-[-.065em]">Maya built a<br />pipeline that listens.</h3><p className="mt-4 max-w-[260px] text-[10px] leading-4 text-black/45">From raw idea to working system. A founder-led sales funnel designed around real customer language.</p><button className="mt-5 flex w-full items-center justify-between border-t border-black/30 pt-3 font-mono text-[8px] uppercase tracking-widest">See how she built it <ArrowUpRight className="h-3.5 w-3.5" /></button></div>
  </div>;
}

function BriefBlueprint() { return <StudyShell dark label="Input / Architecture" footer="A brief is only the first draft of a system."><div className="grid h-[66%] grid-cols-2 border-y border-white/20"><div className="p-4 font-serif text-lg italic leading-tight text-white/55">“We need more qualified conversations without becoming a content machine.”</div><div className="relative border-l border-white/20 p-4">{["Position", "Story", "Path", "Offer"].map((x,i)=><motion.div key={x} initial={{width:0}} whileInView={{width:`${82-i*12}%`}} transition={{delay:i*.2,duration:.8,ease}} className="mb-5 border-t border-[#91a6ff] pt-2 text-xs">0{i+1} &nbsp; {x}</motion.div>)}<div className="absolute bottom-4 right-4 h-20 w-20 border border-white/25"><div className="absolute inset-3 border border-white/25"/><div className="absolute inset-7 bg-[#91a6ff]"/></div></div></div></StudyShell> }
function SignalFinder() { return <StudyShell label="Editorial extraction" footer="Find the signal. Remove the rest."><div className="relative h-[68%] overflow-hidden border-y border-black/20 py-4 font-serif text-[15px] leading-[1.55] text-black/20">{Array.from({length:15},(_,i)=><p key={i}>We help ambitious teams <motion.span whileInView={{color:i===7?"#111":"rgba(0,0,0,.2)"}} transition={{delay:i*.06}} className={i===7?"border-b border-[#667fe0] bg-[#91a6ff]/30":""}>{i===7?"turn attention into action":"find a clearer path to growth"}</motion.span> through strategy, design, and disciplined execution.</p>)}<div className="absolute right-1 top-1/2 font-mono text-[7px] uppercase tracking-widest [writing-mode:vertical-rl]">Line 08 selected</div></div></StudyShell> }
function OfferAnatomy() { return <StudyShell dark label="Offer / Exploded view" footer="The offer is a machine made of promises."><div className="relative flex h-[68%] items-center justify-center">{["Outcome","Method","Proof","Speed"].map((x,i)=><motion.div key={x} initial={{y:0}} whileInView={{y:(i-1.5)*72}} transition={{duration:1,ease}} className="absolute flex h-16 w-[78%] items-center justify-between border border-white/25 bg-[#111] px-4"><span className="font-mono text-[7px] text-white/35">0{i+1}</span><span className="text-xl tracking-[-.05em]">{x}</span><span className="h-2 w-2 rounded-full bg-[#91a6ff]"/></motion.div>)}</div></StudyShell> }
function BuildTimeline() { return <StudyShell label="30 days / Compressed" footer="One idea. Five decisive moments."><div className="relative h-[68%] border-y border-black/20"><div className="absolute left-1/2 top-0 h-full w-px bg-black/20"/>{["Listen","Frame","Make","Test","Launch"].map((x,i)=><motion.div key={x} initial={{opacity:0,x:i%2?-20:20}} whileInView={{opacity:1,x:0}} transition={{delay:i*.18}} className={`absolute w-[45%] ${i%2?"right-0":"left-0 text-right"}`} style={{top:`${8+i*18}%`}}><span className="font-mono text-[7px] text-black/35">Day {String(i*7+1).padStart(2,"0")}</span><p className="text-2xl tracking-[-.06em]">{x}</p><span className={`absolute top-3 h-2 w-2 rounded-full bg-[#7189e9] ${i%2?"-left-[4px]":"-right-[4px]"}`}/></motion.div>)}</div></StudyShell> }
function BeforeSystem() { return <StudyShell label="State change / 01—02" footer="From improvising every time to a system that compounds."><div className="grid h-[68%] grid-cols-2 border-y border-black/20"><div className="relative overflow-hidden border-r border-black/20">{Array.from({length:24},(_,i)=><motion.span key={i} animate={{x:[0,(i%4-2)*8,0],y:[0,(i%3-1)*7,0]}} transition={{duration:3+i%4,repeat:Infinity}} className="absolute h-1.5 w-1.5 rounded-full bg-black" style={{left:`${8+(i*37)%84}%`,top:`${8+(i*53)%84}%`}}/>)}<SmallLabel>Before / fragments</SmallLabel></div><div className="relative"><SmallLabel>After / system</SmallLabel>{[18,34,50,66,82].map((t,i)=><motion.div key={t} initial={{scaleX:0}} whileInView={{scaleX:1}} transition={{delay:i*.15,duration:.7}} className="absolute left-[15%] right-[15%] h-px bg-black" style={{top:`${t}%`}}/>)}<div className="absolute left-1/2 top-[18%] h-[64%] w-px bg-[#7189e9]"/></div></div></StudyShell> }
function AudienceLayers() { return <StudyShell dark label="Audience / Composite portrait" footer="An audience is made of language, not demographics."><div className="relative h-[68%] overflow-hidden border-y border-white/20">{["I need proof","Make it simple","Will this scale?","Show me the path","What changes first?","Can my team run it?"].map((x,i)=><motion.p key={x} initial={{opacity:.15,x:i%2?-30:30}} whileInView={{opacity:1,x:0}} transition={{delay:i*.14}} className="absolute whitespace-nowrap font-serif text-2xl italic" style={{left:`${(i*17)%35}%`,top:`${9+i*14}%`,fontSize:`${18+i*2}px`,opacity:.25+i*.1}}>{x}</motion.p>)}<div className="absolute left-1/2 top-1/2 h-48 w-32 -translate-x-1/2 -translate-y-1/2 rounded-[50%] border border-[#91a6ff]"/></div></StudyShell> }
function DecisionEngine() { return <StudyShell label="Strategy / If—then" footer="Good strategy makes the next move obvious."><div className="flex h-[68%] flex-col justify-center border-y border-black/20">{[["If trust is low","Lead with proof"],["If time is short","Compress the path"],["If intent is high","Open the conversation"]].map(([a,b],i)=><motion.div key={a} initial={{opacity:0}} whileInView={{opacity:1}} transition={{delay:i*.25}} className="grid grid-cols-[1fr_20px_1fr] items-center border-t border-black/20 py-6 first:border-0"><p className="font-serif italic text-black/45">{a}</p><ArrowUpRight className="h-3 w-3"/><p className="text-lg font-medium leading-tight">{b}</p></motion.div>)}</div></StudyShell> }
function ProofStack() { return <StudyShell dark label="Evidence / Momentum" footer="Claims become credible when the proof stacks up."><div className="flex h-[68%] flex-col justify-center border-y border-white/20">{["12 customer interviews","3× reply rate","42 qualified leads","1 repeatable system"].map((x,i)=><motion.div key={x} initial={{x:i%2?-70:70,opacity:0}} whileInView={{x:0,opacity:1}} transition={{delay:i*.16,duration:.7,ease}} className="mx-auto -mt-px flex h-20 w-[82%] items-center justify-between border border-white/25 bg-[#111] px-4" style={{transform:`rotate(${i%2?-2:2}deg)`}}><span className="font-mono text-[7px] text-white/35">0{i+1}</span><p className="text-lg tracking-[-.04em]">{x}</p></motion.div>)}</div></StudyShell> }
function MessageCompression() { return <StudyShell label="378 words → 7" footer="Say less. Make every word carry more."><div className="relative h-[68%] overflow-hidden border-y border-black/20"><div className="font-serif text-[10px] leading-tight text-black/15">{Array.from({length:34},(_,i)=><span key={i}>Strategy should make growth feel less like guesswork and more like a system. </span>)}</div><motion.div initial={{clipPath:"inset(0 50% 0 50%)"}} whileInView={{clipPath:"inset(0 0% 0 0%)"}} transition={{duration:1.2,ease}} className="absolute inset-x-3 top-1/2 -translate-y-1/2 bg-[#e8e8e3] py-6 text-center text-4xl font-medium leading-[.85] tracking-[-.07em]">Attention,<br />made actionable.</motion.div></div></StudyShell> }
function LaunchSequence() { return <StudyShell dark label="Launch / T–04" footer="A campaign does not drop. It unfolds."><div className="flex h-[68%] items-center justify-center border-y border-white/20"><div className="relative h-64 w-64">{[0,1,2,3].map(i=><motion.div key={i} initial={{scale:0,opacity:1}} whileInView={{scale:1,opacity:.15}} transition={{delay:i*.25,duration:1.2}} className="absolute rounded-full border border-[#91a6ff]" style={{inset:`${i*24}px`}}/>)}<div className="absolute inset-0 grid place-items-center text-center"><p className="text-6xl font-medium tracking-[-.08em]">04</p><SmallLabel>Story / Page / Email / Live</SmallLabel></div></div></div></StudyShell> }
function BuilderManifesto() { return <StudyShell label="Builder / Point of view" footer="Introduce builders through what they believe."><div className="flex h-[68%] flex-col justify-between border-y border-black/20 py-5"><p className="font-serif text-4xl italic leading-[.95] tracking-[-.04em]">“I don’t build more content. I build reasons to move.”</p><div><div className="mb-3 h-20 w-20 bg-black [clip-path:polygon(50%_0,100%_35%,82%_100%,18%_100%,0_35%)]"/><p className="text-lg font-medium">Nia Cole</p><SmallLabel>Campaign systems / Chicago</SmallLabel></div></div></StudyShell> }
function SystemXray() { return <StudyShell dark label="Outcome / Under the surface" footer="Reveal the invisible work inside the finished thing."><div className="relative h-[68%] border-y border-white/20">{["Research","Positioning","Narrative","Design","Distribution"].map((x,i)=><motion.div key={x} initial={{width:"18%"}} whileInView={{width:`${90-i*10}%`}} transition={{delay:i*.15,duration:.8,ease}} className="absolute left-0 flex h-12 items-center justify-between border border-white/25 px-3" style={{top:`${8+i*17}%`}}><span className="font-mono text-[7px]">{x}</span><span className="h-1.5 w-1.5 bg-[#91a6ff]"/></motion.div>)}</div></StudyShell> }
function IterationWall() { return <StudyShell label="Versions / 01—12" footer="The final answer is built from better questions."><div className="grid h-[68%] grid-cols-3 gap-2 border-y border-black/20 py-4">{Array.from({length:12},(_,i)=><motion.div key={i} initial={{opacity:0,scale:.8}} whileInView={{opacity:i===11?1:.35,scale:1}} transition={{delay:i*.06}} className={`relative aspect-[3/4] border p-2 ${i===11?"border-[#667fe0] bg-black text-white":"border-black/25"}`}><span className="font-mono text-[6px]">V{String(i+1).padStart(2,"0")}</span><div className="absolute bottom-2 left-2 right-2 space-y-1"><i className="block h-px bg-current"/><i className="block h-px w-2/3 bg-current"/></div></motion.div>)}</div></StudyShell> }
function MetricTranslation() { return <StudyShell dark label="Data / Human meaning" footer="The number matters because somebody did something."><div className="relative flex h-[68%] flex-col justify-center border-y border-white/20"><motion.p initial={{opacity:0,scale:.7}} whileInView={{opacity:1,scale:1}} transition={{duration:.8,ease}} className="text-center text-[96px] font-medium leading-none tracking-[-.1em]">42</motion.p><p className="mt-2 text-center font-serif text-2xl italic text-white/40">qualified leads</p><div className="mx-auto mt-8 h-px w-16 bg-[#91a6ff]"/><p className="mt-8 text-center text-sm leading-5">42 people raised a hand<br />and asked to talk.</p></div></StudyShell> }
function TheHandoff() { return <StudyShell label="Built to continue" footer="The best builder story ends with someone else taking it forward."><div className="relative h-[68%] border-y border-black/20"><div className="absolute left-[10%] right-[10%] top-1/2 h-px bg-black/25"/>{["Builder","Team","System","Next"].map((x,i)=><motion.div key={x} initial={{opacity:0,scale:0}} whileInView={{opacity:1,scale:1}} transition={{delay:i*.3,duration:.5}} className="absolute top-1/2 -translate-x-1/2 -translate-y-1/2 text-center" style={{left:`${12+i*25}%`}}><span className={`mx-auto grid h-12 w-12 place-items-center rounded-full border ${i===3?"border-[#667fe0] bg-[#91a6ff]":"border-black/30 bg-[#e8e8e3]"}`}><ArrowUpRight className="h-3 w-3"/></span><SmallLabel>{x}</SmallLabel></motion.div>)}</div></StudyShell> }

function StudyShell({ dark=false, label, footer, children }: { dark?: boolean; label: string; footer: string; children: React.ReactNode }) { return <div className={`flex h-full flex-col p-5 ${dark?"bg-[#101010] text-white":"bg-[#e8e8e3] text-black"}`}><div className="flex items-center justify-between"><SmallLabel>{label}</SmallLabel><span className="h-1.5 w-1.5 rounded-full bg-[#91a6ff]"/></div><div className="my-auto h-[76%]">{children}</div><div className={`flex items-end justify-between border-t pt-4 ${dark?"border-white/20":"border-black/20"}`}><p className="max-w-[75%] text-2xl font-medium leading-[.95] tracking-[-.055em]">{footer}</p><ArrowDown className="h-4 w-4 opacity-40"/></div></div> }

function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="font-mono text-[8px] uppercase tracking-[.2em] text-current opacity-45">{children}</p>; }
function SmallLabel({ children }: { children: React.ReactNode }) { return <p className="font-mono text-[7px] uppercase tracking-[.18em] opacity-45">{children}</p>; }
function FrameMarks() { return <><span className="pointer-events-none absolute left-2 top-2 z-40 h-2 w-2 border-l border-t border-current opacity-25" /><span className="pointer-events-none absolute right-2 top-2 z-40 h-2 w-2 border-r border-t border-current opacity-25" /><span className="pointer-events-none absolute bottom-2 left-2 z-40 h-2 w-2 border-b border-l border-current opacity-25" /><span className="pointer-events-none absolute bottom-2 right-2 z-40 h-2 w-2 border-b border-r border-current opacity-25" /></>; }
