"use client"

import Image from "next/image"
import { motion, useScroll, useSpring, useTransform } from "framer-motion"
import { useEffect, useState } from "react"
import { ArrowDown, Database, Mail, Radar, Search, Send, Users } from "lucide-react"
import { Container, CTA, ExecutiveDashboard, HeroSystemVisual, KPIGrid, NarrativeSection, PipelineVisualization, ProcessFlow, ScrollReveal, SectionHeader } from "./_components"

export default function Apollo2Page() {
  const { scrollYProgress } = useScroll()
  const progress = useSpring(scrollYProgress, { stiffness: 150, damping: 30 })
  const heroY = useTransform(scrollYProgress, [0,.15], [0,60])
  const [compact,setCompact] = useState(false)
  useEffect(()=>{const update=()=>setCompact(window.scrollY>70); update(); addEventListener("scroll",update,{passive:true}); return()=>removeEventListener("scroll",update)},[])

  return <div className="overflow-hidden bg-white font-geist-sans text-[#1d1d1f] selection:bg-[#147ce5] selection:text-white">
    <motion.div style={{scaleX:progress}} className="fixed left-0 top-0 z-[100] h-[2px] w-full origin-left bg-[#147ce5]"/>
    <motion.nav animate={{height:compact?48:56}} className="fixed inset-x-0 top-0 z-50 border-b border-black/[.06] bg-white/85 backdrop-blur-2xl"><Container className="flex h-full items-center justify-between"><a href="#top" className="text-sm font-semibold">434 Media <span className="font-normal text-[#86868b]">/ Sales OS</span></a><div className="hidden gap-7 text-xs text-[#515154] md:flex"><a href="#process">Process</a><a href="#pipeline">Pipeline</a><a href="#kpis">KPIs</a></div><a href="#system" className="rounded-full bg-[#147ce5] px-4 py-1.5 text-xs font-medium text-white">Explore</a></Container></motion.nav>

    <main>
      <section id="top" className="relative min-h-[100svh] bg-[linear-gradient(180deg,#f4f9ff_0%,#fff_76%)] pt-28"><Container className="text-center"><ScrollReveal><p className="text-sm font-semibold text-[#147ce5]">434 Media Sales Operating System</p><h1 className="mx-auto mt-5 max-w-5xl text-[clamp(3.8rem,9vw,8.5rem)] font-semibold leading-[.89] tracking-[-.078em]">Qualified leads.<br/><span className="bg-gradient-to-r from-[#147ce5] to-[#69aef5] bg-clip-text text-transparent">By design.</span></h1><p className="mx-auto mt-7 max-w-2xl text-lg leading-relaxed text-[#6e6e73] md:text-xl">We turn outbound prospecting into a repeatable system for identifying the right clients, opening meaningful conversations, and building predictable pipeline.</p><div className="mt-8"><CTA href="#system">See how it works <ArrowDown className="ml-2" size={15}/></CTA></div></ScrollReveal></Container><motion.div style={{y:heroY}}><HeroSystemVisual/></motion.div></section>

      <section id="system" className="py-32 md:py-52"><Container><SectionHeader kicker="Why process matters" title={<>Growth cannot depend<br/>on chance.</>} copy="Qualified leads rarely appear consistently without a shared method for deciding who to pursue, when to act, and what happens next."/><div className="mt-24"><NarrativeSection index="01" title="Focus" copy="A defined ideal client profile keeps the team centered on companies and decision-makers with a real reason to buy."/><NarrativeSection index="02" title="Timing" copy="Intent and company signals reveal when a relevant prospect is more likely to be open to a conversation."/><NarrativeSection index="03" title="Consistency" copy="A connected workflow makes follow-up visible, repeatable, and measurable across the entire team."/></div></Container></section>

      <section className="bg-[#f5f5f7] py-32 md:py-52"><Container><div className="grid items-center gap-16 md:grid-cols-[.78fr_1.22fr]"><SectionHeader center={false} kicker="Where Apollo fits" title={<>One tool inside<br/>the system.</>} copy="Apollo supports research, prospecting, contact intelligence, and outreach. It helps us execute the method—it is not the method itself."/><ScrollReveal className="overflow-hidden rounded-[34px] bg-white shadow-[0_30px_100px_rgba(25,45,80,.08)]"><Image src="/apollo2/apollo-product-ui.png" alt="Apollo supporting research and outreach within the broader sales workflow" width={1536} height={1024} className="h-auto w-full mix-blend-multiply"/></ScrollReveal></div><div className="mt-16 grid gap-4 md:grid-cols-4">{[[Search,"Find","Surface contacts that match the ICP."],[Radar,"Prioritize","Use company and intent signals."],[Database,"Organize","Keep research and contact data connected."],[Mail,"Reach out","Launch thoughtful email sequences."]].map(([Icon,title,copy],i)=><ScrollReveal key={title as string} delay={i*.08} className="rounded-2xl bg-white p-6"><Icon className="text-[#147ce5]" size={20}/><h3 className="mt-10 font-semibold">{title as string}</h3><p className="mt-2 text-sm text-[#6e6e73]">{copy as string}</p></ScrollReveal>)}</div></Container></section>

      <section id="process" className="py-32 md:py-52"><Container><SectionHeader kicker="Prospecting framework" title={<>A clear path to the<br/>right conversation.</>} copy="Each step reduces guesswork and gives the next action a reason."/><ProcessFlow/></Container></section>

      <section id="pipeline" className="bg-black py-32 md:py-52"><Container><SectionHeader dark kicker="The pipeline" title={<>Every lead has<br/>a next step.</>} copy="The system carries a prospect from first signal to a long-term relationship, with visible ownership at every handoff."/><PipelineVisualization/></Container></section>

      <section className="py-32 md:py-52"><Container><div className="grid items-center gap-20 md:grid-cols-[.85fr_1.15fr]"><SectionHeader center={false} kicker="Outreach" title={<>Earn the<br/>conversation.</>} copy="We use a personalized single email or a focused three-email sequence to create relevance—not noise."/><ScrollReveal className="overflow-hidden rounded-[32px] border border-black/[.06] shadow-[0_30px_100px_rgba(25,45,80,.08)]"><div className="flex items-center border-b border-black/[.06] px-6 py-4"><span className="text-xs text-[#86868b]">Sequence · 1 of 3</span><span className="ml-auto rounded-full bg-[#eef6ff] px-3 py-1 text-[10px] font-semibold text-[#147ce5]">Personalized</span></div><div className="p-8 md:p-10"><p className="text-xs text-[#86868b]">To: Qualified prospect</p><div className="mt-8 h-3 w-2/3 rounded bg-black/10"/><div className="mt-8 space-y-3">{["100%","91%","96%","70%"].map((width,i)=><motion.div key={width} initial={{width:0}} whileInView={{width}} viewport={{once:true}} transition={{delay:i*.1}} className="h-2 rounded bg-black/[.07]"/>)}</div><button className="mt-10 inline-flex items-center gap-2 rounded-full bg-[#147ce5] px-5 py-2.5 text-xs font-semibold text-white">Send email <Send size={13}/></button></div></ScrollReveal></div></Container></section>

      <section id="kpis" className="bg-[#f5f5f7] py-32 md:py-52"><Container><SectionHeader kicker="Executive dashboard" title={<>Measure the system.<br/>Improve the system.</>} copy="Conversion rates show where momentum is created, where it slows, and where the team should focus next."/><ScrollReveal className="mt-20 rounded-[30px] bg-white p-7 md:p-11"><div className="grid gap-7 md:grid-cols-6">{["Lead → MQL","MQL → SQL","SQL → Discovery","Discovery → Proposal","Proposal → Won","Lead → Customer"].map((label,i)=><div key={label}><div className="flex h-11 w-11 items-center justify-center rounded-full bg-[#eef6ff] text-xs font-semibold text-[#147ce5]">0{i+1}</div><h3 className="mt-5 text-sm font-semibold">{label}</h3><p className="mt-2 text-xs text-[#86868b]">Set baseline</p></div>)}</div><div className="mt-10 h-1.5 overflow-hidden rounded-full bg-black/[.06]"><motion.div initial={{width:0}} whileInView={{width:"78%"}} viewport={{once:true}} transition={{duration:1.4}} className="h-full rounded-full bg-[#147ce5]"/></div><p className="mt-4 text-xs text-[#86868b]">Targets remain open until baseline data is available.</p></ScrollReveal><KPIGrid/><ExecutiveDashboard/></Container></section>

      <section className="relative flex min-h-[82svh] items-center bg-[radial-gradient(circle_at_50%_100%,#d8ecff_0%,#fff_56%)] py-32"><Container className="text-center"><ScrollReveal><p className="text-sm font-semibold text-[#147ce5]">434 Media methodology</p><h2 className="mx-auto mt-5 max-w-5xl text-[clamp(3.6rem,8vw,7.8rem)] font-semibold leading-[.91] tracking-[-.075em]">Consistent systems create predictable growth.</h2><p className="mx-auto mt-8 max-w-xl text-lg text-[#6e6e73]">Define the customer. Find the signal. Earn the conversation. Measure what happens next.</p><div className="mt-9"><CTA href="#top">Review the system <ArrowDown className="ml-2 rotate-180" size={15}/></CTA></div><p className="mt-16 text-xs text-[#86868b]">Presented by 434 Media</p></ScrollReveal></Container></section>
    </main>
  </div>
}
